      PROGRAM TEST_RANDOM_NUMBER
      REAL :: R(5,5)
      CALL INIT_RANDOM_SEED()         ! SEE EXAMPLE OF RANDOM_SEED
      CALL RANDOM_NUMBER(R)
      PRINT *, R
      END PROGRAM

      SUBROUTINE INIT_RANDOM_SEED()
      INTEGER :: I, N, CLOCK
      INTEGER, DIMENSION(:), ALLOCATABLE :: SEED

      CALL RANDOM_SEED(SIZE = N)
      ALLOCATE(SEED(N))

      CALL SYSTEM_CLOCK(COUNT=CLOCK)

      SEED = CLOCK + 37 * (/ (I - 1, I = 1, N) /)
      CALL RANDOM_SEED(PUT = SEED)

      DEALLOCATE(SEED)
      END SUBROUTINE

