      PROGRAM OPENMP_PI_LOCK
      INCLUDE 'omp_lib.h'
      INTEGER I, N, TID
      INTEGER(OMP_LOCK_KIND) LOCK
      DOUBLE PRECISION X, STEP, PI /0.0/, THREAD_SUM /0.0/
      N= 100000000
      STEP = 1.0/N
      CALL OMP_INIT_LOCK(LOCK)
      T1 = OMP_GET_WTIME()
!$OMP PARALLEL PRIVATE(X) FIRSTPRIVATE(THREAD_SUM)
!$OMP DO
      DO I=1, N
        X = (I-0.5)*STEP
        THREAD_SUM = THREAD_SUM + 1.0/SQRT(1.0-X*X)
      END DO
!$OMP END DO
      CALL OMP_SET_LOCK(LOCK)
      PI = PI + STEP * THREAD_SUM
      CALL OMP_UNSET_LOCK(LOCK)
!$OMP END PARALLEL
      T2 = OMP_GET_WTIME()
      PRINT *, 'computational time: ', T2-T1, 's'
      CALL OMP_DESTROY_LOCK(LOCK)
      WRITE(*,*) PI
      END
